seed: 42
torch_deterministic: True

origin_shape: 27 #env origin
proprioception_shape: 23  #proprio 
encoded_observation_shape: 39 # encoded = proprio + latent
latent_shape: 16
PCDownSampleNum: 4096
TDownSampleNum: 64

rl_algo: "sac"
rl_iter: 10000
lr: 0.0001


policy: # only works for MlpPolicy right now
  # training params
  hidden_nodes: 512
  hidden_layer: 3
  activation: elu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid

  
learn:
  save_interval: 200 # check for potential saves every this many iterations
  max_iterations: 20000
