model_list:
  - - Resnet
    - 18 # (18, 34, 50, 101)
  - - Densenet
    - 169 # (121, 161, 169, 201)
model_choice: 1
image_type: RGB # RGB or GRAY
train_mode: True
test_object: False
mixed_image: True

data_dir: ../Dataset
save_dir: ../saved_models

weights:
  - - _05-14_17-36-54 # Resnet
    - 87 # epoch
  - - _06-26_14-58-36 # Densenet
    - 132 # epoch
eval_batch: 32

cuda_index: 0
batch_size: 64
num_epoch: 200
learning_rate: 5.0e-4

regularization: False
weight_decay: 0

img_size:
  - 345
  - 460