seed: 42

clip_observations: 5.0
clip_actions: 1.0

env_shape: 5
proprioception_shape: 18
load_iter: 1000

learn:
  test: False
  resume: 0
  save_interval: 300
  print_log: True

  # rollout params
  max_iterations: 50000

  # training params
  hidden_nodes: 512
  hidden_layer: 3

  cliprange: 0.2
  nsteps: 8
  noptepochs: 1
  nminibatches: 4 # this is per agent
  replay_size: 2000
  polyak: 0.99
  learning_rate: 0.001
  max_grad_norm: 1
  ent_coef: 0.2
  reward_scale: 1
  batch_size: 32

  gamma: 0.98


  log_interval: 1
  asymmetric: False
